In [2]:
import pandas as pd

In [3]:

df = pd.read_csv('data/investments_VC.csv', encoding='latin-1')
print(df.shape)
print(df.info())

(54294, 39)
<class 'pandas.DataFrame'>
RangeIndex: 54294 entries, 0 to 54293
Data columns (total 39 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   permalink             49438 non-null  str
 1   name                  49437 non-null  str
 2   homepage_url          45989 non-null  str
 3   category_list         45477 non-null  str
 4    market               45470 non-null  str
 5   funding_total_usd     49438 non-null  str
 6   status                48124 non-null  str
 7   country_code          44165 non-null  str
 8   state_code            30161 non-null  str
 9   region                44165 non-null  str
 10  city                  43322 non-null  str
 11  funding_rounds        49438 non-null  float64
 12  founded_at            38554 non-null  str
 13  founded_month         38482 non-null  str
 14  founded_quarter       38482 non-null  str
 15  founded_year          38482 non-null  float64
 16  first_funding_at      49438 non-null  str
 17  last_funding_at       49438 non-null  str
 18  seed                  49438 non-null  float64
 19  venture               49438 non-null  float64
 20  equity_crowdfunding   49438 non-null  float64
 21  undisclosed           49438 non-null  float64
 22  convertible_note      49438 non-null  float64
 23  debt_financing        49438 non-null  float64
 24  angel                 49438 non-null  float64
 25  grant                 49438 non-null  float64
 26  private_equity        49438 non-null  float64
 27  post_ipo_equity       49438 non-null  float64
 28  post_ipo_debt         49438 non-null  float64
 29  secondary_market      49438 non-null  float64
 30  product_crowdfunding  49438 non-null  float64
 31  round_A               49438 non-null  float64
 32  round_B               49438 non-null  float64
 33  round_C               49438 non-null  float64
 34  round_D               49438 non-null  float64
 35  round_E               49438 non-null  float64
 36  round_F               49438 non-null  float64
 37  round_G               49438 non-null  float64
 38  round_H               49438 non-null  float64
dtypes: float64(23), str(16)
memory usage: 16.2 MB
None

In [4]:
df.columns = df.columns.str.strip()

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 54294 entries, 0 to 54293
Data columns (total 39 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   permalink             49438 non-null  str
 1   name                  49437 non-null  str
 2   homepage_url          45989 non-null  str
 3   category_list         45477 non-null  str
 4   market                45470 non-null  str
 5   funding_total_usd     49438 non-null  str
 6   status                48124 non-null  str
 7   country_code          44165 non-null  str
 8   state_code            30161 non-null  str
 9   region                44165 non-null  str
 10  city                  43322 non-null  str
 11  funding_rounds        49438 non-null  float64
 12  founded_at            38554 non-null  str
 13  founded_month         38482 non-null  str
 14  founded_quarter       38482 non-null  str
 15  founded_year          38482 non-null  float64
 16  first_funding_at      49438 non-null  str
 17  last_funding_at       49438 non-null  str
 18  seed                  49438 non-null  float64
 19  venture               49438 non-null  float64
 20  equity_crowdfunding   49438 non-null  float64
 21  undisclosed           49438 non-null  float64
 22  convertible_note      49438 non-null  float64
 23  debt_financing        49438 non-null  float64
 24  angel                 49438 non-null  float64
 25  grant                 49438 non-null  float64
 26  private_equity        49438 non-null  float64
 27  post_ipo_equity       49438 non-null  float64
 28  post_ipo_debt         49438 non-null  float64
 29  secondary_market      49438 non-null  float64
 30  product_crowdfunding  49438 non-null  float64
 31  round_A               49438 non-null  float64
 32  round_B               49438 non-null  float64
 33  round_C               49438 non-null  float64
 34  round_D               49438 non-null  float64
 35  round_E               49438 non-null  float64
 36  round_F               49438 non-null  float64
 37  round_G               49438 non-null  float64
 38  round_H               49438 non-null  float64
dtypes: float64(23), str(16)
memory usage: 16.2 MB

In [6]:
drop_cols = [
    'permalink',
    'name',
    'homepage_url'
]

df = df.drop(columns=drop_cols)

In [7]:
df['status'].value_counts(dropna=False)

status
operating    41829
NaN           6170
acquired      3692
closed        2603
Name: count, dtype: int64

In [8]:
df[df['status'].isna()][
    ['funding_total_usd', 'funding_rounds']
].describe()

       funding_rounds
count     1314.000000
mean         1.535769
std          1.123324
min          1.000000
25%          1.000000
50%          1.000000
75%          2.000000
max         10.000000

In [9]:
df['status'].isna().sum()

np.int64(6170)

In [10]:
df[df['status'].isna()][[
    'first_funding_at',
    'last_funding_at'
]].describe(include='all')

       first_funding_at last_funding_at
count              1314            1314
unique              693             609
top          2012-09-01      2013-09-01
freq                 19              21

In [11]:
df[df['status'].isna()]['founded_year'].describe()

count     918.000000
mean     2006.142702
std         9.494664
min      1947.000000
25%      2005.000000
50%      2010.000000
75%      2012.000000
max      2014.000000
Name: founded_year, dtype: float64

## We separate dataset according to status of the startups

1. Unknown Labels Startups
2. Operating labels Startups
3. acquired or closed labels Startups

In [13]:
labeled_df = df[df['status'].isin(['acquired', 'closed'])].copy()
operating_df = df[df['status'] == 'operating'].copy()
unknown_df = df[df['status'].isna()].copy()

In [15]:
labeled_df['status'].value_counts()

status
acquired    3692
closed      2603
Name: count, dtype: int64